{
 "title": "simple dashboard",
 "description": "simplest dashboard for example",
 "time": { "from": "2023-04-09T06:31:56.317Z", "to": "2023-11-05T20:01:07.801Z" },
 "templating": {
  "list": [
   {
    "name": "mapped_veh_id",
    "query": "select distinct  mapped_veh_id  from train t ;"
   },
   {
    "name": "track_or_stop",
    "label": "track_or_stop",
    "query": "select distinct track_or_stop from train;"
   }
  ]
 },
 "panels": [
  {
   "title": "last position of trains",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\nwith foo as (\nselect\n\tmax(timestamps_utc) as time,\n\tmapped_veh_id\nfrom\n\ttrain t1\nwhere\n\tt1.timestamps_utc > '2023-09-10'\ngroup by\n\tmapped_veh_id )\nselect\n\ttimestamps_utc ,\n\ttrack_or_stop ,\n\tlat,\n\tlon,\n\tt.mapped_veh_id\nfrom\n\ttrain t,\n\tfoo f\nwhere\n\tt.timestamps_utc = f.time\n\tand track_or_stop in ($track_or_stop)\n\tand t.mapped_veh_id in ($mapped_veh_id)\n\tand f.mapped_veh_id = t.mapped_veh_id\norder by 1, 2, 3, 4"
    }
   ]
  },
  {
   "title": "avg temp by train",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n$__timeGroupAlias(timestamps_utc, 1h),\navg(RS_E_InAirTemp_PC1) AS RS_E_InAirTemp_PC1\nFROM train\nWHERE\n  $__timeFilter(timestamps_utc)\n  and mapped_veh_id in ($mapped_veh_id)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "last value of air temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  $__timeGroup(timestamps_utc, 5m) as time,\n  avg (RS_E_InAirTemp_PC1) as foo\nfrom train \nwhere $__timeFilter(timestamps_utc)\ngroup by 1\norder by 1 "
    }
   ]
  },
  {
   "title": "Number of Trains",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with foo as (SELECT Distinct\n  mapped_veh_id\nFROM\n  train\nWHERE \n  $__timeFilter(timestamps_utc)  \n)\nselect count(*) from foo"
    }
   ]
  }
 ]
}