{
 "title": "Specific Dashboard",
 "description": "Dashboard to keep track of the workings of an especific train",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "mapped_veh_id",
    "label": "mapped_veh_id",
    "query": "select distinct mapped_veh_id from train;"
   },
   {
    "name": "interpolation",
    "label": "interpolation",
    "query": "select * from (values ('1d'),('1h'),('10m'),('1m'),('1s'))as foo;"
   }
  ]
 },
 "panels": [
  {
   "title": "Get location of a train",
   "type": "geomap",
   "description": "get last 2000 points of the train grouped by 1 minute and ",
   "gridPos": { "h": 24, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n$__timeGroupAlias(timestamps_utc, $interpolation),\navg(lat) as lat,\navg(lon) as lon\nFROM train\nWHERE\n  $__timeFilter(timestamps_utc)\n  and mapped_veh_id = $mapped_veh_id \nGROUP BY 1\nORDER BY 1 desc\nlimit 10000;"
    }
   ]
  },
  {
   "title": "Air temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n\t$__timeGroupAlias(timestamps_utc, $interpolation ),\n\tavg(rs_e_inairtemp_pc1) as \"air temp pc1\",\n\tavg(rs_e_inairtemp_pc2) as \"air temp pc2\",\n\tavg(temp) as \"weather air temp\"\nfrom\n\ttrain\nwhere\n\t$__timeFilter(timestamps_utc)\n\tand mapped_veh_id in ($mapped_veh_id)\ngroup by\n\t1\norder by\n\t1;"
    }
   ]
  },
  {
   "title": "Oil Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n\t$__timeGroupAlias(timestamps_utc, $interpolation ),\n\tavg(rs_e_oilpress_pc1) as \"oil pressure pc1\",\n\tavg(rs_e_oilpress_pc2) as \"oil pressure pc2\"\nfrom\n\ttrain\nwhere\n\t$__timeFilter(timestamps_utc)\n\tand mapped_veh_id in ($mapped_veh_id)\ngroup by\n\t1\norder by\n\t1;"
    }
   ]
  },
  {
   "title": "Water temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n\t$__timeGroupAlias(timestamps_utc, $interpolation ),\n\tavg(rs_e_wattemp_pc1) as \"water temp pc1\",\n\tavg(rs_e_wattemp_pc2) as \"water temp pc2\"\nfrom\n\ttrain\nwhere\n\t$__timeFilter(timestamps_utc)\n\tand mapped_veh_id in ($mapped_veh_id)\ngroup by\n\t1\norder by\n\t1;"
    }
   ]
  },
  {
   "title": "Water temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n\t$__timeGroupAlias(timestamps_utc, $interpolation ),\n\tavg(rs_e_wattemp_pc1) as \"water temp pc1\",\n\tavg(rs_e_wattemp_pc2) as \"water temp pc2\"\nfrom\n\ttrain\nwhere\n\t$__timeFilter(timestamps_utc)\n\tand mapped_veh_id in ($mapped_veh_id)\ngroup by\n\t1\norder by\n\t1;"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 16 },
   "targets": [
    {
     "rawSql": "select\n\t$__timeGroupAlias(timestamps_utc, $interpolation ),\n\tavg(rs_e_rpm_pc1) as \"rpm pc1\",\n\tavg(rs_e_rpm_pc2) as \"rpm pc2\"\nfrom\n\ttrain\nwhere\n\t$__timeFilter(timestamps_utc)\n\tand mapped_veh_id in ($mapped_veh_id)\ngroup by\n\t1\norder by\n\t1;"
    }
   ]
  },
  {
   "title": "Stop",
   "type": "timeseries",
   "description": "Spike if the train is marked as stopped",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "targets": [
    {
     "rawSql": "select\n\t$__timeGroupAlias(timestamps_utc, $interpolation ),\n\tmax(track_or_stop) as \"stop\"\nfrom\n\ttrain\nwhere\n\t$__timeFilter(timestamps_utc)\n\tand mapped_veh_id in ($mapped_veh_id)\ngroup by\n\t1\norder by\n\t1;"
    }
   ]
  }
 ]
}